### ISSUE TITLE
关于raw.githubusercontent.com

### ISSUE THREAD

**Issue by walkeryou2** [0-01/0#10]
代码i，host已修改，两个ip都尝试了，依然无效
关闭自动配置可使用快捷下载

电信

**Comment by 0-01** [comment]
如果连接 raw.githubusercontent.com 出错，将影响检查更新、获取快捷下载和分享下载参数。如果出错，最新版将自动改用本地下载参数。因此，如果现在参数没有改变，不会影响下载，只会影响检查是否有新版本。

可以忽略此错误，并取消修改 Hosts 。
