### ISSUE TITLE
你好，这个以后能增加个限速下载的功能吗

### ISSUE THREAD

**Issue by ericshehong** [0-01/0#15]
如题。

**Comment by 0-01** [comment]
**工具/aria2 配置**里的**全局最大下载速度**
**工具/aldl 配置** 里的 **每连接的最大速率**

**快捷下载**和**分享下载**的设置和上述类似。

**Comment by ericshehong** [comment]
感谢解答------------------ 原始邮件 ------------------
发件人: "0-01"<notifications@github.com>
发送时间: 2019年12月22日(星期天) 晚上7:00
收件人: "0-01/0"<0@noreply.github.com>;
抄送: "ericshehong"<ericshehong@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [0-01/0] 你好，这个以后能增加个限速下载的功能吗 (#15)



工具/aria2 配置里的全局最大下载速度
 工具/aldl 配置 里的 每连接的最大速率
 
快捷下载和分享下载的设置和上述类似。
 
&mdash;
