### ISSUE TITLE
可以ping通raw.githubusercontent.com但是还是提示出错。

### ISSUE THREAD

**Issue by lukemin** [0-01/0#27]
C:\Windows\system32>ping raw.githubusercontent.com

正在 Ping raw.githubusercontent.com [151.101.0.133] 具有 32 字节的数据:
来自 151.101.0.133 的回复: 字节=32 时间=110ms TTL=53
来自 151.101.0.133 的回复: 字节=32 时间=110ms TTL=53
来自 151.101.0.133 的回复: 字节=32 时间=110ms TTL=53
请求超时。

151.101.0.133 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 3，丢失 = 1 (25% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 110ms，最长 = 110ms，平均 = 110ms

错误代码:u

**Comment by 0-01** [comment]
v0.1.0070 版已不再提示此提示。
