### ISSUE TITLE
有没有可能支持代理功能

### ISSUE THREAD

**Issue by 1608637229** [0-01/0#3]
比如我是用ssr代理。开全局依然不能走代理。

**Comment by 0-01** [comment]
你是想下载的时候走代理吗？那速度不是更慢了吗？先出去，在进来，兜一圈，还要花费代理流量。
如果非要这样做，aria2 有 --all-proxy=<PROXY> 设置代理的选项，可以将其添加到 aria2\aria2.conf 里，但这样做有悖常理。

**Comment by 1608637229** [comment]
> 你是想下载的时候走代理吗？那速度不是更慢了吗？先到外面兜一圈，还要消耗代理流量。
> 如果非要这样做，aria2 有设置代理的选项 --all-proxy= ，可以将其添加到 aria2\aria2.conf 里，但这样做有悖常理。

为什么不支持国外啊，这软件如果是国外或者港台的ip直接就打开报错了。

**Comment by 0-01** [comment]
当前版本尚未达到可发布的状态，连账号登录还没有解决，一时半会很难支持海外地区。

**Comment by 2bitO** [comment]
可以用Proxifier指定作者的程序走代理,代理设置为本地ss/v2的端口号就可以了
