### ISSUE TITLE
希望下载的时候能够保持原来的目录结构

### ISSUE THREAD

**Issue by GaisaiYuno** [0-01/0#34]
下的速度非常快，感觉都有点对不起百度了。

美中不足的是目录结构没有保持，每次都得重新整理文件。

**Comment by GaisaiYuno** [comment]
还有就是希望aria2下载错误的文件能够自动再用saldl尝试一遍

**Comment by Jesselee0322** [comment]
这个软件太厉害了

**Comment by 0-01** [comment]
请参见 https://github.com/0-01/0/issues/18
