### ISSUE TITLE
创建下载队列出错，提示sign error, 错误代码：31362

### ISSUE THREAD

**Issue by abel3839** [0-01/0#37]
如下图所示，下载分享资源不管用aria2还是saldl下载创建队列时都会报这个错，下载的资源是：
链接:https://pan.baidu.com/s/1eA-dMr1-oGgKuRCvPPLzAQ 提取码:h26j 
其他资源还未发现有此问题

![image](https://user-images.githubusercontent.com/32889915/72809524-c10f7c80-3c96-11ea-95f6-5adb8a3c5e71.png)

**Comment by 0-01** [comment]
此问题已在 v0.1.0070 版中解决。
