### ISSUE TITLE
下载大一点的文件会出现错误

### ISSUE THREAD

**Issue by GaisaiYuno** [0-01/0#38]
比如https://pan.baidu.com/s/1N4TrMIU2kc4XNWW6WZ7Lrg cwxp

**Comment by GaisaiYuno** [comment]
大小在300~400MB时还是正常的。

**Comment by hyq3351** [comment]
> 比如https://pan.baidu.com/s/1N4TrMIU2kc4XNWW6WZ7Lrg cwxp

aria2下载错误，用saldl下载

**Comment by GaisaiYuno** [comment]
> > 比如https://pan.baidu.com/s/1N4TrMIU2kc4XNWW6WZ7Lrg cwxp
> 
> aria2下载错误，用saldl下载

saldl试了也不行

**Comment by hyq3351** [comment]
![image](https://user-images.githubusercontent.com/54705050/72956226-e35de300-3dd9-11ea-8ec2-d8a64808b428.png)
saldl刚下完

**Comment by hyq3351** [comment]
不行就换个链接 你这个链接我saldl可以下

**Comment by GaisaiYuno** [comment]
> ![image](https://user-images.githubusercontent.com/54705050/72956226-e35de300-3dd9-11ea-8ec2-d8a64808b428.png)
> saldl刚下完

![sdfsdf](https://user-images.githubusercontent.com/52853137/72956300-30da5000-3dda-11ea-9f29-af2c1db28c95.PNG)
但是我就变成一堆乱码了

**Comment by hyq3351** [comment]
> > ![image](https://user-images.githubusercontent.com/54705050/72956226-e35de300-3dd9-11ea-8ec2-d8a64808b428.png)
> > saldl刚下完
> 
> ![sdfsdf](https://user-images.githubusercontent.com/52853137/72956300-30da5000-3dda-11ea-9f29-af2c1db28c95.PNG)
> 但是我就变成一堆乱码了

这不是乱码 这就在下载 你稍微拖动一下就看到下载速度了 不行看任务管理器下载速度 等一会就自己下好了

**Comment by GaisaiYuno** [comment]
> > > ![image](https://user-images.githubusercontent.com/54705050/72956226-e35de300-3dd9-11ea-8ec2-d8a64808b428.png)
> > > saldl刚下完
> > 
> > 
> > ![sdfsdf](https://user-images.githubusercontent.com/52853137/72956300-30da5000-3dda-11ea-9f29-af2c1db28c95.PNG)
> > 但是我就变成一堆乱码了
> 
> 这不是乱码 这就在下载 你稍微拖动一下就看到下载速度了 不行看任务管理器下载速度 等一会就自己下好了

好的谢谢！

希望作者能修一下那个乱码 @0-01。

**Comment by jyuan15** [comment]
同一账号网盘中文件，用“分享下载saldl”，有些文件能下，虽然命令窗口是乱码，但很快就下完了，但有些文件却提示108错误？
