### ISSUE TITLE
下载时弹出的命令窗口全乱码

### ISSUE THREAD

**Issue by jyuan15** [0-01/0#41]
根本看不出任何内容，也没别的地方能看下载进度，请问怎么设置才能正常显示？

**Comment by wlnwl** [comment]
请检查命令行编码，看看是gbk还是utf-8

**Comment by Albertliu2012** [comment]
下载完成，最后会显示complete

**Comment by 0-01** [comment]
如果用的是saldl，那不是乱码，是进度。可以向上滚动命令提示符，会显示当前速度和进度。
