### ISSUE TITLE
关于程序自动识别分享链接的问题

### ISSUE THREAD

**Issue by 2333333333-X** [0-01/0#47]
发现程序有一个自动识别分享链接的功能，很不错，方便
比如这一段复杂的文本：
百度云盘链接：https://pan.baidu.com/s/1112222333 密码: 2333，下载xxxapp，使用更方便哦
可以自动识别成：https://pan.baidu.com/s/1112222333 2333的格式
但只有在这个分享链接是https的情况下，这个功能才会生效
在http的情况下呢？
比如说这个链接，它是15年的时候生成的，http://pan.baidu.com/s/1jHBvmp4 密码: g1jk
这种就不能自动识别了

**Comment by 0-01** [comment]
这是一个bug，我已找到，下一版修复
