### ISSUE TITLE
关于寻人,有个建议

### ISSUE THREAD

**Issue by Genxgen** [0-01/0#50]

**Comment by Genxgen** [comment]
主要觉得 作者现在这个方法寻人效率太低.
出贴目的想促成作者成功寻人
1.虽然有照片,但要知道一个女孩 化妝/ 打扮/ 发型/ 衣着都可以使外型看起差別很大,既然立心要寻人,別介怀公布点资料, 建议给出生出年份范围(例如:1960-1965),和生活经历 (何年何月在什么地方工作)等, 这样可以更大程度促使 別人帮助你找出你要寻的人.

2.如果寻的人在国內,现在的微信 的市佔率, 参考现在流行的关注公众号方式:
   使用软件就关注公众号 + 朋友圈怎转发寻人 文章 
   这样可能 增力成功率

3.寻人 文章 --
  可以写一下你的故事,也许更多人感动而主动转发,即使他不用软件

最后 , 时间不等人, 过了某年期, 找到了也许只能问好,所以要抓紧 , 祝你 早寻到人!

**Comment by 666emmm** [comment]
有照片吗？我找不到作者在哪发寻人消息，想帮转都不知道发啥

**Comment by Genxgen** [comment]
Google 软件名 + 照片
